### ISSUE TITLE
Output files switched

### ISSUE THREAD

**Issue by Aisha-D** [eastgenomics/eggd_starfusion#3]
Output files are outputted the other way around 
![Screenshot from 2023-03-06 15-44-36](https://user-images.githubusercontent.com/45298626/223159546-e125acce-6d0d-4114-a528-7700af429443.png)

**Comment by corbin-chris** [comment]
Being worked on: https://github.com/eastgenomics/eggd_starfusion/pull/4

**Comment by Aisha-D** [comment]
I closed it but did not see the changes for this :upside_down_face: I merged too quickly sorry!

**Comment by corbin-chris** [comment]
I left it out sorry :100: it's in this one: https://github.com/eastgenomics/eggd_starfusion/pull/5
